apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: default
  labels:
    app: service-d
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: service-d
        image: k8s-poc/service-d:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
          name: http
        resources:
          requests:
            memory: "384Mi"    # Moderately over-provisioned for light-medium load (50 req/s)
            cpu: "120m"        # Moderately over-provisioned - actual usage ~30-40m
          limits:
            memory: "768Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
        env:
        - name: JAVA_OPTS
          value: "-Xms1g -Xmx2g"
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
  labels:
    app: service-d
spec:
  selector:
    app: service-d
  ports:
  - name: http
    port: 80
    targetPort: 8083
    nodePort: 30083  # Expose on node port 30083
  type: NodePort